Tradingzone3/Models/Broker.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Tradingzone3.Models {

    [Table("tblBroker")]
    public class Broker {
        [Column("broker_id")]
        public int BrokerId { get; set; }

        [Column("broker_name")]
        public string BrokerName { get; set; }

        [Column("broker_type")]
        public string BrokerType { get; set; }

        [Column("brokerage")]
        public double Brokerage { get; set; }

        [Column("firm_id")]
        public int FirmId { get; set; }

    }
}

Tradingzone3/Models/BrokerContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Tradingzone3.Models {
    public class BrokerContext : DbContext {

        public DbSet<Broker> Brokers { get; set; }
        public DbSet<Firm> Firms { get; set; }
    }
}

Tradingzone3/Models/Firm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Tradingzone3.Models {

    [Table("tblFirm")]
    public class Firm {

        [Column("firm_id")]
        public int FirmId { get; set; }

        [Column("firm_name")]
        public string FirmName { get; set; }

        public List<Broker> Brokers { get; set; }
    }
}

Tradingzone3/Controllers/BrokerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tradingzone3.Models;

namespace Tradingzone3.Controllers
{
    public class BrokerController : Controller
    {
        public ActionResult Index(int id) {
            BrokerContext brokerContext = new BrokerContext();
            List<Broker> brokers = brokerContext.Brokers.Where(brk => brk.FirmId == id).ToList();
            return View(brokers);
        }

        public ActionResult Details(int id)
        {
            //Broker broker = new Broker()
            //{
            //    BrokerId = 1,
            //    BrokerName = "John",
            //    BrokerType = "FIX",
            //    Brokerage = 3.5
            //};
            BrokerContext brokerContext = new BrokerContext();
            Broker broker = brokerContext.Brokers.Single(bkr => bkr.BrokerId == id);

            return View(broker);
        }

    }
}

Tradingzone3/Controllers/FirmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tradingzone3.Models;

namespace Tradingzone3.Controllers
{
    public class FirmController : Controller
    {
        //
        // GET: /Firm/

        public ActionResult Index()
        {
            BrokerContext brokerContext = new BrokerContext();
            return View(brokerContext.Firms.ToList());
        }

    }
}

Tradingzone3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tradingzone3.Models;

namespace Tradingzone3.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            BrokerContext brokerContext = new BrokerContext();
            return View(brokerContext.Brokers.ToList());
        }

    }
}

Tradingzone3/Views/Broker/Details.cshtml
@model Tradingzone3.Models.Broker

@{
    ViewBag.Title = "Broker Details";
}

<h2>Broker Details</h2>
<table style="font-family: Calibri">
    <tr>
        <td><b>Broker ID</b></td>
        <td>@Model.BrokerId</td>
    </tr>
    <tr>
        <td><b>Broker Name</b></td>
        <td>@Model.BrokerName</td>
    </tr>
    <tr>
        <td><b>Broker Type</b></td>
        <td>@Model.BrokerType</td>
    </tr>
    <tr>
        <td><b>Brokerage</b></td>
        <td>@Model.Brokerage</td>
    </tr>
</table>
@Html.ActionLink("Back to list", "Index" , new { id = @Model.FirmId})

Tradingzone3/Views/Broker/Index.cshtml
@using Tradingzone3.Models
@model IEnumerable<Tradingzone3.Models.Broker>

@{
    ViewBag.Title = "Broker List";
}
<div style="font-family: calibri">
    <h2>Broker List</h2>
    <ul>
        @foreach (Broker broker in @Model)
        {
            <li>@Html.ActionLink(broker.BrokerName, "Details", new { @id = broker.BrokerId }) </li>
        }
    </ul>
@Html.ActionLink("Back to Firm List", "Index", "Firm", null, null)
</div>

Tradingzone3/Views/Firm/Index.cshtml
@using Tradingzone3.Models
@model IEnumerable<Tradingzone3.Models.Firm>

@{
    ViewBag.Title = "Firm List";
}

<h2>Firm List</h2>
<table>
    @foreach (Firm firm in @Model)
    {
        <tr>
            <td>@Html.ActionLink(firm.FirmName, "Index", "Broker", new { id = firm.FirmId}, null) </td>
        </tr>
    }
</table>

Tradingzone3/Views/Home/Index.cshtml
@using Tradingzone3.Models
@model IEnumerable<Broker> 

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@foreach (Broker broker in Model.ToList())
{
    <table style="font-family: Calibri">
    <tr>
        <td><b>Broker ID</b></td>
        <td>@broker.BrokerId</td>
    </tr>
    <tr>
        <td><b>Broker Name</b></td>
        <td>@broker.BrokerName</td>
    </tr>
    <tr>
        <td><b>Broker Type</b></td>
        <td>@broker.BrokerType</td>
    </tr>
    <tr>
        <td><b>Brokerage</b></td>
        <td>@broker.Brokerage</td>
    </tr>
</table>

}
@Html.ActionLink("Back to Firm List", "Index", "Firm")

Tradingzone3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>